[book]
authors = ["Leonardo Moura et al."]
language = "en"
multilingual = false
src = "src"
title = "TrustBonds Docs"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
