name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install deps
        run: |
          pnpm install
          cd packages/contracts
          forge install

      - name: Check gas snapshots
        run: pnpm snapshot-check

      - name: Run tests
        run: pnpm test
